services:
  mongo:
    image: mongo:7
    container_name: jellyfsch-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - jellyfsch-mongo-data:/data/db

volumes:
  jellyfsch-mongo-data:
