services:
  mongo:
    image: mongo:7
    container_name: fschchat-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - fschchat-mongo-data:/data/db

volumes:
  fschchat-mongo-data:
